### PR TITLE
Add Champagne Wishes; update Better Junimos Forestry + Redux, Fishing Info Overlays, and Working Fireplace

### PR DESCRIPTION
**Pull request by GitHub-Sysadmin**

### CODE REVIEW

**Comment by GitHub-Sysadmin** [comment]
Contacted author to send updated file to remove failed check

**Review by DespairScent — COMMENTED** [review]
Not sure if this is how unofficial updates are defined (Convenient Inventory). See [24h Clock](https://github.com/Pathoschild/SmapiCompatibilityList/blob/5bc5cfcbeb66528681ad2f65064bd4eb13d49c71/data/mods.jsonc#L5) or [Advanced Melee Framework](https://github.com/Pathoschild/SmapiCompatibilityList/blob/5bc5cfcbeb66528681ad2f65064bd4eb13d49c71/data/mods.jsonc#L380).

Also, I don't think the unofficial "Convenient Inventory" update is worth including here. The original works quite well with the latest version of the game, there is only one bug that does not even cause a crash.

**Comment by GitHub-Sysadmin** [comment]
> Not sure if this is how unofficial updates are defined (Convenient Inventory). See [24h Clock](https://github.com/Pathoschild/SmapiCompatibilityList/blob/5bc5cfcbeb66528681ad2f65064bd4eb13d49c71/data/mods.jsonc#L5) or [Advanced Melee Framework](https://github.com/Pathoschild/SmapiCompatibilityList/blob/5bc5cfcbeb66528681ad2f65064bd4eb13d49c71/data/mods.jsonc#L380).

Well spotted
> Also, I don't think the unofficial "Convenient Inventory" update is worth including here. The original works quite well with the latest version of the game, there is only one bug that does not even cause a crash.

What's the procedure for a bug-fix version of a mod hosted outside of nexus mods?

**Comment by DespairScent** [comment]
> What's the procedure for a bug-fix version of a mod hosted outside of nexus mods?

I guess it's up to the "updater" to decide. I just left it on the nexus, those who need it will find it. I said "it's not worth including here" because of "broken" and "incompatible" clarification [here](https://github.com/Pathoschild/SmapiCompatibilityList?tab=readme-ov-file#unofficial-updates). I don't really understand what exactly is meant by this, but IMHO it means that the mod is completely unusable or abandoned. The original mod isn't dead, I think the author will update it soon, they just can't at the moment.

**Comment by Pathoschild** [comment]
I made a few little changes:
- Removed the Convenient Inventory unofficial update per the above discussion, and because forks using the same unique ID don't have a separate entry on the list.
- Moved Champagne Wishes to `broken-content-packs.jsonc` and corrected its info.
- Fixed the unofficial update for Better Junimos Forestry Redux being listed under Better Junimos Forestry.
- Fixed some `http://` links to use `https://`.

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Thanks again for the help! The update should be live in a few minutes.

**Pull request merged**
